[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "google-api-python-client>=2.172.0",
    "pydub>=0.25.1",
    "reportlab>=4.4.1",
    "speechrecognition>=3.14.3",
]
